# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/nexys4.xdc

# IP: ip/numbers/numbers.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==numbers || ORIG_REF_NAME==numbers} -quiet] -quiet
