# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir H:/Documents/ES3B2/lab5_a/lab5_a.cache/wt [current_project]
set_property parent.project_path H:/Documents/ES3B2/lab5_a/lab5_a.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo h:/Documents/ES3B2/lab5_a/lab5_a.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{H:/Documents/ES3B2/images/death star/ds_image.coe}}
add_files {{H:/Documents/ES3B2/images/death star/ds_color_map.coe}}
add_files H:/Documents/ES3B2/images/bird/bird_red.coe
add_files H:/Documents/ES3B2/images/bird/bird_green.coe
add_files H:/Documents/ES3B2/images/bird/bird_blue.coe
add_files {{H:/Documents/ES3B2/images/bird small/smallbird_red.coe}}
add_files {{H:/Documents/ES3B2/images/bird small/smallbird_green.coe}}
add_files {{H:/Documents/ES3B2/images/bird small/smallbird_blue.coe}}
add_files H:/Documents/ES3B2/images/pipe/pipeedit_red.coe
add_files H:/Documents/ES3B2/images/pipe/pipeedit_green.coe
add_files H:/Documents/ES3B2/images/pipe/pipeedit_blue.coe
add_files H:/Documents/ES3B2/images/pipe/pipeedit2_red.coe
add_files //doozer.ads.warwick.ac.uk/User64/u/u1905040/Documents/ES3B2/images/pipe/pipeedit2_green.coe
add_files H:/Documents/ES3B2/images/pipe/pipeedit2_blue.coe
add_files H:/Documents/ES3B2/images/Heights/heights.coe
add_files H:/Documents/ES3B2/images/Heights/pipe_heights.coe
add_files {{H:/Documents/ES3B2/images/bird tiny/birdtiny_red.coe}}
add_files {{H:/Documents/ES3B2/images/bird tiny/birdtiny_green.coe}}
add_files {{H:/Documents/ES3B2/images/bird tiny/birdtiny_blue.coe}}
add_files H:/Documents/ES3B2/images/background/backgroundc_red.coe
add_files H:/Documents/ES3B2/images/background/backgroundc_blue.coe
add_files H:/Documents/ES3B2/images/background/backgroundc_green.coe
add_files H:/Documents/ES3B2/images/background/bot_red.coe
add_files H:/Documents/ES3B2/images/background/bot_green.coe
add_files H:/Documents/ES3B2/images/background/bot_blue.coe
add_files H:/Documents/ES3B2/images/infobar/infobar_red.coe
add_files H:/Documents/ES3B2/images/infobar/infobar_green.coe
add_files H:/Documents/ES3B2/images/infobar/infobar_blue.coe
add_files H:/Documents/ES3B2/images/fb/fb_r.coe
add_files H:/Documents/ES3B2/images/fb/fb_g.coe
add_files H:/Documents/ES3B2/images/fb/fb_b.coe
add_files {{H:/Documents/ES3B2/images/pipe new/pipe_red.coe}}
add_files {{H:/Documents/ES3B2/images/pipe new/pipe_green.coe}}
add_files {{H:/Documents/ES3B2/images/pipe new/pipe_blue.coe}}
add_files H:/Documents/ES3B2/images/bottom/bottom2_red.coe
add_files H:/Documents/ES3B2/images/bottom/bottom2_green.coe
add_files H:/Documents/ES3B2/images/bottom/bottom2_blue.coe
add_files H:/Documents/ES3B2/images/bottom/bottom_small_red.coe
add_files H:/Documents/ES3B2/images/bottom/bottom_small_green.coe
add_files H:/Documents/ES3B2/images/bottom/bottom_small_blue.coe
add_files H:/Documents/ES3B2/images/numbers/numbers.coe
add_files H:/Documents/ES3B2/images/numbers/numbers1.coe
add_files H:/Documents/ES3B2/images/numbers/nums.coe
add_files H:/Documents/ES3B2/images/gameover/gameover_red.coe
add_files H:/Documents/ES3B2/images/gameover/gameover_green.coe
add_files H:/Documents/ES3B2/images/gameover/gameover_blue.coe
read_verilog -library xil_defaultlib {
  H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/new/drawcon.v
  H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/new/movecon.v
  H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/new/vga.v
  H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/new/game_top.v
}
read_ip -quiet H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/numbers/numbers.xci
set_property used_in_implementation false [get_files -all h:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/numbers/numbers_ooc.xdc]

read_ip -quiet H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all h:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all h:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all h:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/bird_red/bird_red.xci
set_property used_in_implementation false [get_files -all h:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/bird_red/bird_red_ooc.xdc]

read_ip -quiet H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/bird_blue/bird_blue.xci
set_property used_in_implementation false [get_files -all h:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/bird_blue/bird_blue_ooc.xdc]

read_ip -quiet H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/bird_green_2/bird_green.xci
set_property used_in_implementation false [get_files -all h:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/bird_green_2/bird_green_ooc.xdc]

read_ip -quiet H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/pipe_red/pipe_red.xci
set_property used_in_implementation false [get_files -all h:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/pipe_red/pipe_red_ooc.xdc]

read_ip -quiet H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/pipe_green/pipe_green.xci
set_property used_in_implementation false [get_files -all h:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/pipe_green/pipe_green_ooc.xdc]

read_ip -quiet H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/pipe_blue/pipe_blue.xci
set_property used_in_implementation false [get_files -all h:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/pipe_blue/pipe_blue_ooc.xdc]

read_ip -quiet H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/heights/heights.xci
set_property used_in_implementation false [get_files -all h:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/heights/heights_ooc.xdc]

read_ip -quiet H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/bg_red/bg_red.xci
set_property used_in_implementation false [get_files -all h:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/bg_red/bg_red_ooc.xdc]

read_ip -quiet H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/bg_blue/bg_blue.xci
set_property used_in_implementation false [get_files -all h:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/bg_blue/bg_blue_ooc.xdc]

read_ip -quiet H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/bg_green/bg_green.xci
set_property used_in_implementation false [get_files -all h:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/bg_green/bg_green_ooc.xdc]

read_ip -quiet H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/info_red/info_red.xci
set_property used_in_implementation false [get_files -all h:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/info_red/info_red_ooc.xdc]

read_ip -quiet H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/info_green_1/info_green.xci
set_property used_in_implementation false [get_files -all h:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/info_green_1/info_green_ooc.xdc]

read_ip -quiet H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/info_blue_1/info_blue.xci
set_property used_in_implementation false [get_files -all h:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/info_blue_1/info_blue_ooc.xdc]

read_ip -quiet H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/over_red/over_red.xci
set_property used_in_implementation false [get_files -all h:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/over_red/over_red_ooc.xdc]

read_ip -quiet H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/over_green/over_green.xci
set_property used_in_implementation false [get_files -all h:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/over_green/over_green_ooc.xdc]

read_ip -quiet H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/over_blue/over_blue.xci
set_property used_in_implementation false [get_files -all h:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/over_blue/over_blue_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc H:/Documents/ES3B2/lab5_a/lab5_a.srcs/constrs_1/new/nexys4.xdc
set_property used_in_implementation false [get_files H:/Documents/ES3B2/lab5_a/lab5_a.srcs/constrs_1/new/nexys4.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top game_top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef game_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file game_top_utilization_synth.rpt -pb game_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
