# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/pipe_green/pipe_green.xci
# IP: The module: 'pipe_green' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/pipe_green/pipe_green_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pipe_green'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: H:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/pipe_green/pipe_green.xci
# IP: The module: 'pipe_green' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Documents/ES3B2/lab5_a/lab5_a.srcs/sources_1/ip/pipe_green/pipe_green_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pipe_green'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
